Email : **merajul.islam.khan.bd@gmail.com**

In [1]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


### Answer To The Q1

Q1. Create NumPy arrays from the ages and salaries data generated above. Print both arrays and display their dtype, ndim, shape, and size.

In [2]:
npage = np.array(ages)
npsalari = np.array(salaries)
print(npage)
print(npsalari)

print(npage.dtype)
print(npsalari.dtype)

print(npage.ndim)
print(npsalari.ndim)

print(npage.shape)
print(npsalari.shape)

print(npage.size)
print(npsalari.size)

[56 46 32 25 38 56 36 40 28 28]
[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
int64
int64
1
1
(10,)
(10,)
10
10


## Answer Of Q2

Q2. Using the salaries array, find and print the highest and lowest salary values. Also, calculate and print the average salary and age using NumPy functions.


In [3]:
sal = np.array(salaries)
msal = max(sal)
mnsal = min(sal)
print(f"Max Salary: {msal}")
print(f"Min Salary: {mnsal}")

avsal = np.average(sal)
avag = np.average(npage)

print(f"Average Salaray: {avsal}")
print(f"Average Age: {avag}")

Max Salary: 89735
Min Salary: 30769
Average Salaray: 57446.9
Average Age: 38.5


## Answer Of Q3

 From the ages array, filter and print all ages greater than 30 using a boolean condition. Then count and print how many employees are older than 30.


In [4]:
fage = npage[npage > 30]
print(fage)
print(f"Employees older than 30: {fage.size}")

[56 46 32 38 56 36 40]
Employees older than 30: 7


## Answer Of Q4

Q4. Create a new NumPy array that increases every employee’s age by 5 years (without modifying the original array). Print the new updated ages array.


In [5]:
upage = npage + 5
print(upage)
# print(npage)

[61 51 37 30 43 61 41 45 33 33]


## Answer Of Q5

 Q5. Using NumPy, calculate the total salary expense (sum of all salaries) and the difference between the maximum and minimum salary. Print both results.


In [6]:
tsal = np.sum(npsalari)
mxsal = np.max(npsalari);
mnsal = np.min(npsalari)
print(tsal)
print(mxsal - mnsal)

574469
58966


## Answer of Q6

Q6. Load the employees.csv file into a Pandas DataFrame. Display the first 5 rows, and check basic info using info() and summary statistics using describe().


In [18]:
df = pd.read_csv("employees.csv")
print(df.head())

print("Dataframe Info: ",df.info())

print("Dataframe Describe",df.describe())

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes
Dataframe Info:  None
Dataframe Describe              id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000


## Answer Of Q7

Q7. Display only the id, age, and salary columns. Then show the last 3 rows using tail().


In [22]:
sdf = df[["id",'age','salary']]
print(sdf)

print(sdf.tail(3))

   id  age  salary
0   1   56   77191
1   2   46   74131
2   3   32   46023
3   4   25   71090
4   5   38   31685
5   6   56   30769
6   7   36   89735
7   8   40   86101
8   9   28   32433
9  10   28   35311
   id  age  salary
7   8   40   86101
8   9   28   32433
9  10   28   35311


## Answer Of Q8

Q8. Filter the DataFrame to show only employees who work in the IT department. Print the result and show the total number of IT employees.


In [25]:
idf = df.loc[df['dept'] == 'IT']
print(idf)
print("Total Number of IT employees:" ,len(idf))

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT
Total Number of IT employees: 3


## Answer of Q9

 Sort the DataFrame by salary in descending order and display the top 3 highest-paid employees along with their department and age.


In [37]:
sdf = df.sort_values(by ='salary',ascending=False)
print(sdf[['dept','age','salary']].head(3))

      dept  age  salary
6  Finance   36   89735
7       IT   40   86101
0       HR   56   77191


## Answer of Q10

Q10. Replace all salary values greater than 80000 with 80000 using loc. Then calculate and print the new average salary of all employees after replacement.


In [47]:
df.loc[df["salary"] > 80000, "salary"] = 80000
avg_sal = df["salary"].mean()
print(avg_sal)

55863.3
